#server:
#  port: 9092
#
#spring:
#  profiles:
#    active: dev
#  application:
#    name: FOOD-CATALOGUE-SERVICE
#  datasource:
#    url: jdbc:mysql//localhost:3306/foodcataloguedb
#    username: root
#    password: secret
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
#    show-sql: true
#    properties:
#      hibernate:
#        dialect:  org.hibernate.dialect.MySQL8InnoDBDialect
##    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect