spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodcataloguedb
    username: root
    password: secret

client:
  service-url:
    defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0